micropython/micropython-lib

- contextlib/contextlib.py
- contextlib/metadata.txt
- contextlib/setup.py
- contextlib/tests.py
> contextlib: port ExitStack from CPython 3.4

- umqtt.simple/umqtt/simple.py
IMHO there is no need to close the socket in `ping()` and it  break the MQTT connection.
> umqtt.simple: do not close the socket in ping()

- uasyncio.core/uasyncio/core.py
- uasyncio/test_echo.py
- uasyncio/uasyncio/__init__.py
Thank you so much Damien, Paul and the MicroPython community for this amazing project!
Since I read about this project and found a few weeks back that python3.5 can be run in the esp8266 (with less than 64kb of memory), I was immediatelly hook. Once esp8266 gained uselect it seemed that with a little more effort uasyncio was in reach and made a POC (https://github.com/mzdaniel/micropython-lib/tree/uasyncio-esp8266_poc). Here is the revised PR after utimeq landed on the esp. Tested with the latest MicroPython v1.8.6-247-g05aebb9-dirty on 2016-12-26 on an Olimex board.
> uasyncio on esp8266

- micropython/bluetooth/aioble/README.md
- micropython/bluetooth/aioble/aioble/client.py
Reported by @andrewleech
If a client subscribes and then a notification arrives before they await notified(), then they won't see the notification as it won't get dispatched to any registered Characteristic objects.
With this fix, in this scenario the first await to notified() will now immediately return the value that arrived in the meantime.
> micropython/bluetooth/aioble: subscribe must register the connection.

- micropython/bluetooth/aioble/README.md
- micropython/bluetooth/aioble/aioble/client.py
- micropython/bluetooth/aioble/aioble/server.py
- micropython/bluetooth/aioble/multitests/ble_notify.py
- micropython/bluetooth/aioble/multitests/ble_notify.py.exp
After a client does a successful `await char.notified()`, then before the
next call to `notified()` a notification arrives, then they call
`notified()` twice before the _next_ notification, the second call will
return None rather than waiting.
This applies the same fix as in 5a86aa58662469c789effc7f76225889b6a969fe
which solved a similar problem for server-side `char.written()`. Using
a deque is slightly overkill here, but it's consistent with the server
side, and also makes it very easy to support having a notification queue
in the future.
Also makes the client characteristic properly flags/properties-aware (i.e.
explicitly fail operations that aren't supported).
Signed-off-by: Jim Mussared <jim.mussared@gmail.com>
> aioble: Fix notified/indicated event waiting.

- python-stdlib/fnmatch/fnmatch.py
- python-stdlib/fnmatch/metadata.txt
- python-stdlib/fnmatch/setup.py
- python-stdlib/fnmatch/test_fnmatch.py
- python-stdlib/unittest/metadata.txt
- python-stdlib/unittest/setup.py
- python-stdlib/unittest/test_unittest.py
- python-stdlib/unittest/test_unittest_isolated.py
- python-stdlib/unittest/unittest.py
- python-stdlib/unittest/unittest_discover.py
PR primary goal is to provide `discover` argument matching cpython/unittest module.
Also improves other compatibility with cpython, mostly around running as a module (`micropython-coverage -m unittest`) and test stdout format.
This is sitting on top of https://github.com/micropython/micropython-lib/pull/487 and also includes some related module fixes which should get split out into separate PR's.
I also plan to investifate splitting `discover` and hopefully the rest of the new dependencies into a separate module (with auto-import on use like in uasyncio) that can be left out of deployment to device to reduce size if desired.
> Unittest: Extend cpython compatility including discover command

- python-stdlib/fnmatch/fnmatch.py
- python-stdlib/fnmatch/metadata.txt
- python-stdlib/fnmatch/setup.py
- python-stdlib/fnmatch/test_fnmatch.py
Removes dependency on re-pcre which is only available on unix port.
Used in #488
> fnmatch: Add ure compatibility.

- micropython/aiorepl/README.md
- micropython/aiorepl/aiorepl.py
- micropython/aiorepl/manifest.py
This provides an async REPL with the following features:
- Run interactive REPL in the background.
- Execute statements using await.
- Simple history.
See documentation and example here https://github.com/jimmo/micropython-lib/tree/aiorepl/micropython/aiorepl
> micropython/aiorepl: Add an asynchronous REPL.

- README.md
- micropython/mip/manifest.py
- micropython/mip/mip.py
- python-stdlib/uu/manifest.py
- tools/build.py
This PR adds:
- A library (`mip`) that can be frozen (or manually installed) on network-capable boards for on-device installation of packages from micropython-lib (or other similar package indices).
- A tool (`tools/build.py`) to deploy micropython-lib to a static web server suitable for access from `mip` (or `mpremote` when similar functionality is added).
The structure of the static web server output is explained in the comments at the top of deploy.py.
`mip.install()` supports the following use cases:
- `mip.install("foo")` -- this will download the latest version of the foo package (and dependencies) from micropython-lib.
- `mip.install("foo", version="x.y")` -- install foo version x.y, including dependencies at the version when foo x.y was published
- `mip.install("foo", …
> micropython/mip: Add a new `mip` library for on-device installation.

- python-stdlib/os-path/manifest.py
- python-stdlib/os-path/os/path.py
The current `os.path.exists()` function uses `os.access()` which is only provided in the ffi os module, not in `uos`.
```
anl@STEP: ~ $ micropython
MicroPython v1.18-305-g587339022 on 2022-04-11; linux [GCC 9.4.0] version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import os
>>> os.access
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'access'
>>>
```
Also, `is_dir` requries the stat module from micropython-lib
> os.path: Remove ffi os.access usage in exists().

- micropython/drivers/storage/sdcard/sdcard.py
Originally by @peterhinch.
See https://github.com/micropython/micropython/pull/6007 for discussion.
The summary is that on some cards (especially older Kingston ones) if the bus is shared with other SPI devices, then it seems to require that MISO is high for a few cycles before the transaction is initiated.
Because CS is high, this change should otherwise be a no-op.
> sdcard: Set MISO high before readblocks/writeblocks.

- micropython/drivers/radio/nrf24l01/nrf24l01test.py
Use explicit pin numbers to instantiate the SPI interface on RP2. On ESP32 use SoftSPI(...) rather than SPI(-1, ...).
Update terminology to initiator/responder.
Tested with two Pico boards.
> nrf24l01test.py: Add RP2 support, fix ESP32.

- python-stdlib/logging/examples/basic_example.py
- python-stdlib/logging/examples/root_logger.py
- python-stdlib/logging/logging.py
Previously a child logger just uses the global default when unset. Modified to matches the CPython behavior of using the parent's level.
Also implemented CPython's getEffectiveLevel() which provides a convenient way to implement this. In our version, we only ever have one parent (the root), so it only has to recurse one level.
Also set the default level to WARNING to match CPython.
Updated the examples to highlight the differences (but they now match).
> logging: Fall back to root logger level for unset child.

- micropython/bundles/README.md
- micropython/bundles/bundle-networking/manifest.py
This is designed to be a common set of packages that all boards with networking support should include.
Signed-off-by: Jim Mussared <jim.mussared@gmail.com>
> micropython/bundles: Add a bundle-networking meta-package.

- micropython/bluetooth/aioble-central/manifest.py
- micropython/bluetooth/aioble/aioble/central.py
- micropython/bluetooth/aioble/manifest.py
I'm working on using BLE to connect to a Blackmagic Camera and have discovered that in it's advertising packets it will never send it's Complete Local Name (denoted by `0x09`), opting to only send it's Shortened Local Name (denoted by `0x08`).  I've made it so a `ScanResult` will prioritize returning the Complete Local Name, then attempt to fall back to the shortened variant before ultimately returning an empty string.
**Bluetooth Specification Reference**
The [Assigned Numbers Document](https://www.bluetooth.com/specifications/assigned-numbers/) identifies the fields/values for both names as Common Data Types in Section 2.3.  The variants of Local Name are described in Part A, Section 1.2 of the [Core Specification Supplement](https://www.bluetooth.com/specifications/specs/core-specificat …
> aioble: add short name support to scan results

- .github/workflows/build_packages.yml
- .github/workflows/cleanup_published_packages.yml
- CONTRIBUTING.md
- README.md
- tools/ci.sh
Opt-in feature to make it easier for folks to test packages that are still in development, open in Pull Requests, or even in independent forks.
*EDIT: Instructions are now in the PR contents*
This work was funded through GitHub Sponsors.
> ci: Support publishing package & index files to GitHub Pages.

- python-stdlib/unittest-discover/manifest.py
- python-stdlib/unittest-discover/unittest/__main__.py
- python-stdlib/unittest/manifest.py
- python-stdlib/unittest/unittest/__init__.py
Currently if no tests are found when running `unittest discover` then nothing at all is written to stdout, leading you to think it's not working at all.
cpython unittest does display a `0 tests run` sort of output in this scenareo, this PR ensures our package does the same.
> unittest-discover: Print results when no tests are found/run.

- micropython/drivers/bus/onewire/manifest.py
- micropython/drivers/codec/wm8960/manifest.py
- micropython/drivers/display/lcd160cr/manifest.py
- micropython/drivers/display/ssd1306/manifest.py
- micropython/drivers/led/neopixel/manifest.py
- micropython/drivers/radio/nrf24l01/manifest.py
- micropython/drivers/sensor/dht/manifest.py
- micropython/drivers/sensor/ds18x20/manifest.py
- micropython/drivers/sensor/hts221/manifest.py
- micropython/drivers/sensor/lps22h/manifest.py
- micropython/drivers/storage/sdcard/manifest.py
- micropython/net/ntptime/manifest.py
- micropython/net/webrepl/manifest.py
- micropython/senml/manifest.py
- python-ecosys/cbor2/manifest.py
- python-ecosys/iperf3/manifest.py
- python-ecosys/pyjwt/manifest.py
- python-ecosys/urequests/manifest.py
- tools/build.py
- tools/makepyproject.py
This PR adds a mechansim to allow micropython-lib packages to be published to PyPI for use by CPython.
The idea is that there are some packages (in the micropython directory) that do not have CPython counterparts -- essentially our version is the "original" or "upstream" for these packages. As opposed to a package in the python-stdlib or python-ecosys directories, where the micropython-lib is our version of those packages -- if you were using CPython you'd use the "real" one instead.
This adds a tool that can parse a package's manifest and generate a Python project directory (with pyproject.toml) suitable for building and uploading to PyPI. (Note this requires https://github.com/micropython/micropython/pull/11162 to be merged first).
This is enabled for the micropython/senml package which …
> senml: Allow publishing to PyPI as micropython-senml. 

- micropython/bluetooth/aioble-client/manifest.py
- micropython/bluetooth/aioble-server/manifest.py
- micropython/bluetooth/aioble/aioble/client.py
- micropython/bluetooth/aioble/aioble/server.py
- micropython/bluetooth/aioble/manifest.py
Follow up to https://github.com/micropython/micropython/pull/11239
- Removes the workaround for https://github.com/micropython/micropython/issues/6864.
- Sets the default flags for discovered descriptors to be WRITE, so that d.write() will implicitly set response=True.
> aioble: Fix descriptor flag handling.

- micropython/aioespnow/README.md
- micropython/aioespnow/aioespnow.py
- micropython/aioespnow/manifest.py
The `aioespnow` module provides asyncio support for the `espnow` module on ESP32 and ESP8266 ports.
`aioespnow` is a supplementary module which extends the micropython `espnow` module to provide
`asyncio` support.
- Asyncio support is available on all ESP32 targets as well as those ESP8266 boards which include the `uasyncio` module (ie. ESP8266 devices with at least 2MB flash storage).
See the documentation in `micropython-lib/micropython/aioespnow/README.md`.
> aioespnow: New module to provide asyncio support for espnow module.

- micropython/lora/README.md
- micropython/lora/examples/reliable_delivery/README.md
- micropython/lora/examples/reliable_delivery/lora_rd_settings.py
- micropython/lora/examples/reliable_delivery/receiver.py
- micropython/lora/examples/reliable_delivery/receiver_async.py
- micropython/lora/examples/reliable_delivery/sender.py
- micropython/lora/examples/reliable_delivery/sender_async.py
- micropython/lora/examples/simple_rxtx/README.md
- micropython/lora/examples/simple_rxtx/simple_rxtx.py
- micropython/lora/examples/simple_rxtx/simple_rxtx_async.py
- micropython/lora/lora-async/lora/async_modem.py
- micropython/lora/lora-async/manifest.py
- micropython/lora/lora-sx126x/lora/sx126x.py
- micropython/lora/lora-sx126x/manifest.py
- micropython/lora/lora-sx127x/lora/sx127x.py
- micropython/lora/lora-sx127x/manifest.py
- micropython/lora/lora-sync/lora/sync_modem.py
- micropython/lora/lora-sync/manifest.py
- micropython/lora/lora/lora/__init__.py
- micropython/lora/lora/lora/modem.py
- micropython/lora/lora/manifest.py
- micropython/lora/tests/test_time_on_air.py
Working LoRa drivers for:
* SX1276, SX1277, SX1278, SX1279 modems
* SX1261, SX1262 modems.
Eventual goal (not in this PR) is to have enough support for MicroPython to be a LoRaWAN Class A device with a fully async API available.
The [lora README added in the PR branch](https://github.com/projectgus/micropython-lib/blob/feature/lora/micropython/lora/README.md) has instructions for how to use the LoRa drivers.
However, until the PR is merged you need some additional steps to install the lora MicroPython packages.
The `--index` argument of mip install is [needed to install packages from a PR branch](https://github.com/micropython/micropython-lib/#installing-packages-from-forks).
Example:
```sh
$ mpremote connect /dev/ttyUSB0 mip install --index …
```
> micropython/lora: Add async-capable LoRa modem driver

- python-stdlib/bisect/manifest.py
- python-stdlib/json/manifest.py
- python-stdlib/keyword/manifest.py
- python-stdlib/types/manifest.py
Curiously the stdlib/types module missed getting a manifest file in the big migration from [setup.py](https://github.com/micropython/micropython-lib/commit/ecef7a506ccbf31bbbdc0369d17f1d09543e0442#diff-d230118eba5a373e8601695ff1152c9c938687d82cf42cf214ac14ec78432082) to [manifest.py](https://github.com/micropython/micropython-lib/commit/ce66e701) perhaps because it was missing the metadata.txt and only had [setup.py](https://github.com/micropython/micropython-lib/blob/a18d49cda7a5d615298e8bb65fb24208036befff/python-stdlib/types/setup.py)
> types: Add manifest file.

- python-stdlib/logging/logging.py
I noticed recently that the current `log.exception()` function doesn't always print the tracebacks of the exception.
The current handling requires your build to be compiled with `MICROPY_PY_SYS_EXC_INFO` which is not always on by default.
This PR allows you to pass an exception object in as the `exc_info` kwarg (cpython allows this) so the following works regarless of the above build setting.
``` python
try:
run_func()
except Exception as ex:
log.exception("run_func failed", exc_info=ex)
```
Separately to that, currently even when `sys.exc_info()` is enabled, it's only printing the traceback to `_stream` = `sys.stderr` - not to the configured logging handlers. This means for instance if you've got a file log handler, it misses out on the tracebacks.
This PR also addresses this.
> stdlib/logging: Add full support for logging exception tracebacks.

- python-stdlib/copy/manifest.py
`types` module is used here: https://github.com/micropython/micropython-lib/blob/7128d423c2e7c0309ac17a1e6ba873b909b24fcc/python-stdlib/copy/copy.py#L51
Fixes https://github.com/micropython/micropython-lib/issues/679
> python-stdlib/copy: Declare dependency on types.

- micropython/aiorepl/aiorepl.py
f-strings aren't enabled on all builds (e.g. low-flash ESP8266).
Fixes #688
> aiorepl: Replace f-string with str.format.

- python-stdlib/datetime/datetime.py
- python-stdlib/json/json/__init__.py
- unix-ffi/cgi/cgi.py
It is inserted automatically during publish/freezing and having this here prevents the automatic process from happening.
See https://github.com/orgs/micropython/discussions/11838
> all: Remove __version__ from .py files.

- python-stdlib/fnmatch/fnmatch.py
- python-stdlib/fnmatch/manifest.py
With the recent micropython change to remove the `u` prefix by default on builtins (https://github.com/micropython/micropython/pull/11740) the format checker in fnmatch which was detecting `ure` no longer works. 
The MR updates the module to filter the regex automatically as needed.
> stdlib/fnmatch: Fix compatibility with ure -> re.

- .github/workflows/build_packages.yml
- .github/workflows/cleanup_published_packages.yml
- .github/workflows/code_formatting.yml
- micropython/aioespnow/aioespnow.py
- micropython/bluetooth/aioble/examples/l2cap_file_client.py
- micropython/bluetooth/aioble/examples/l2cap_file_server.py
- micropython/drivers/codec/wm8960/wm8960.py
- micropython/drivers/imu/bmi270/bmi270.py
- micropython/drivers/imu/bmm150/bmm150.py
- micropython/drivers/imu/lsm6dsox/lsm6dsox.py
- micropython/drivers/imu/lsm6dsox/lsm6dsox_mlc.py
- micropython/drivers/imu/lsm9ds1/lsm9ds1.py
- micropython/lora/examples/simple_rxtx/simple_rxtx.py
- micropython/lora/examples/simple_rxtx/simple_rxtx_async.py
- micropython/lora/lora-sx126x/lora/sx126x.py
- micropython/lora/lora/lora/modem.py
- micropython/senml/examples/custom_record.py
- micropython/senml/examples/gateway_actuators.py
- micropython/senml/senml/senml_pack.py
- micropython/senml/senml/senml_record.py
- pyproject.toml
- python-ecosys/cbor2/cbor2/encoder.py
- python-ecosys/iperf3/iperf3.py
- python-ecosys/requests/requests/__init__.py
As hinted at https://github.com/micropython/micropython/pull/10977#issuecomment-1531559631
[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.
The ruff Action uses minimal steps to run in ~5 seconds, rapidly providing intuitive GitHub Annotations to contributors.
> all: Lint Python code with ruff.

- .github/workflows/code_formatting.yml
- .github/workflows/ruff.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- tools/codeformat.py
1. Simplify codeformat.py back to be the same as the main repo version, but without .c/.h support. (It's pretty much just a wrapper around `black` now)
2. Add pre-commit support (same as main repo).
3. Split the ruff action into its own CI action (same as main repo).
> Add pre-commit support for micropython-lib.

- micropython/drivers/display/lcd160cr/lcd160cr_test.py
Fixes linter warning [E721](https://beta.ruff.rs/docs/rules/type-comparison/), which was expanded in Ruff 823 to include direct comparison against built-in types.
This is the micropython-lib version of https://github.com/micropython/micropython/pull/12196
---
This work was funded by GitHub sponsors.
> drivers/display/lcd160cr: Use isinstance() for type checking.

- micropython/lora/README.md
- micropython/lora/lora-async/lora/async_modem.py
- micropython/lora/lora-async/manifest.py
- micropython/lora/lora/lora/modem.py
- micropython/lora/lora/manifest.py
It's not necessary to know which pin triggered the IRQ, and it saves some code size.
Noticed while making changes for #572, but is actually an unrelated change.
---
This work was funded through GitHub Sponsors.
> lora: Remove the pin parameter from IRQ callback.

- micropython/lora/README.md
- micropython/lora/lora-stm32wl5/lora/stm32wl5.py
- micropython/lora/lora-stm32wl5/manifest.py
- micropython/lora/lora-sx126x/lora/sx126x.py
- micropython/lora/lora-sx126x/manifest.py
- micropython/lora/lora/lora/__init__.py
- micropython/lora/lora/manifest.py
Adds a LoRa driver for the STM32WL5 "SUBGHZ" LoRa modem, which is essentially a combined SX1261 & SX1262 attached to a custom interface inside the SoC.
This PR depends on Micropython built with https://github.com/micropython/micropython/pull/9130 for the hardware level support.
* ~~Fix HP TX power issue (see https://github.com/micropython/micropython-lib/pull/572#issuecomment-1529490736)~~ - Root cause remains unknown, have noted it in the README and the driver source.
This work was funded through GitHub Sponsors.
> micropython/lora: Add stm32wl5 modem driver

- micropython/bluetooth/aioble-server/manifest.py
- micropython/bluetooth/aioble/aioble/server.py
- micropython/bluetooth/aioble/manifest.py
- micropython/bluetooth/aioble/multitests/ble_buffered_characteristic.py
- micropython/bluetooth/aioble/multitests/ble_buffered_characteristic.py.exp
Updated version of #629 (adds a test and slightly simplifies the argument handling). I'm not too fussed about the backwards compatibility here because the existing behavior was broken, it never should have been read=True by default, rather it should have been `write=True`. (The whole point of the buffered characteristic is to allow the client to _write_ larger values, and optionally have them accumulated via the append flag).
---
Previously a BufferedCharacteristic could only be read by the client, where it should have been writeable. This makes it support all ops (read / write / write-with-response, etc).
Adds a test to check the max_len and append functionality of BufferedCharacteristic.
> aioble/server.py: Allow BufferedCharacteristic to support all ops.

- python-ecosys/requests/manifest.py
- python-ecosys/requests/requests/__init__.py
Chunked detection does not work on current Micropython as it never has an `__iter__` attribute to a generator. It does add `__next__` to them, so this test in `urequests` for chunked detection did not work. I've changed it to `__next__`. I can post a failing example in the PR.
> Fix chunked_data requests in urequests.py

- .github/workflows/ruff.yml
- .pre-commit-config.yaml
The `--format` flag was changed to `--output-format` in the recent update.
Pin to this version to prevent further updates from breaking (e.g. through new rules or other changes).
> .github/workflows/ruff.yml: Pin to 0.1.0.

- unix-ffi/re/re.py
PCRE is marked as EOL and won't receive any new security update.
Convert the re module to PCRE2 API to enforce security. Additional dependency is now needed with uctypes due to changes in how PCRE2 return the match_data in a pointer and require special handling.
The converted module is tested with the test_re.py with no regression.
> unix-ffi: re: convert to PCRE2

- .github/workflows/commit_formatting.yml
- .pre-commit-config.yaml
- tools/ci.sh
- tools/verifygitlog.py
This adds verifygitlog.py from the main repo, adds it to GitHub workflows, and also pre-commit.
I spent a considerable amount of effort trying to make `gitlint` (https://jorisroovers.com/gitlint) work (for both the main repo and here) but it was not flexible enough to make it work with our rules. See https://github.com/jimmo/micropython/tree/gitlint-config
The three main limitations were:
- I ended up having to write a non-trivial amount of Python code as custom rules.
- It doesn't have a way to link to documentation or add suggestions like verifygitlog.py does.
- I couldn't find a way to make `WIP` and `!fix` commits work in pre-commit but not in CI.
So in the end it's just easier to keep using verifygitlog.py (even if it means duplicating it here).
_This work was funded through GitHub …
> tools/verifygitlog.py: Add git commit message checking.

- micropython/drivers/display/lcd160cr/manifest.py
This is the last remaining use of the "options" feature. Nothing in the main repo which `require()`'s this package sets it.
> lcd160cr: Remove support for options in manifest.

- python-stdlib/time/README.md
Attempts to at least partially assist with the problem raised in #725.
> time: Add README to explain the purpose of the time extension library.

- micropython/aiorepl/README.md
- micropython/aiorepl/aiorepl.py
- micropython/aiorepl/manifest.py
I've been using aiorepl daily on my work project and could no longer live without it. I have however been missing some features of the built in repl, so worked to add them here!
The most regular issue I run into is needing to update / fix the line I've just typed! So this PR adds left/right cursor support with character insertion / deletion. This includes the redraw-to-end-of line stuff needed to keep the terminal looking correct.
I considered adding some python functions to the existing readline functionality in micropython, however I think trying to break out a suitable api of readline / repl interface parts suitable for use in something like this would take some effort and and code bulk not used by many users.
Another limitation I've found quite difficult lately is the inability to …
> aiorepl features: cursor, paste and raw mode.

- micropython/uaiohttpclient/example.py
- micropython/uaiohttpclient/manifest.py
- micropython/uaiohttpclient/uaiohttpclient.py
I was getting an error using `uaiohttpclient` and it was due to it hard coding port 80 for the target host. This PR makes a trivial change to split `host:port` if present in the URL. I thought it also sensible to update all the `yield from` to `await` everywhere and of course preface those functions `async`. I made a couple of other minor changes which were suggested by ruff and flake8, i.e. a variable `l` I changed to `ln` and there was a comment > 80 chars which I wrapped.
> uaiohttpclient: parse port instead of hard code 80

- python-ecosys/aiohttp/README.md
- python-ecosys/aiohttp/aiohttp/__init__.py
- python-ecosys/aiohttp/aiohttp/aiohttp_ws.py
- python-ecosys/aiohttp/examples/client.py
- python-ecosys/aiohttp/examples/compression.py
- python-ecosys/aiohttp/examples/get.py
- python-ecosys/aiohttp/examples/headers.py
- python-ecosys/aiohttp/examples/methods.py
- python-ecosys/aiohttp/examples/params.py
- python-ecosys/aiohttp/examples/ws.py
- python-ecosys/aiohttp/examples/ws_repl_echo.py
- python-ecosys/aiohttp/manifest.py
Implement an updated version of `uaiohttpclient` (renamed `aiohttp`) with `ClientSession`, `WebSocketClient` and `SSLContext` support, which is mostly compatible with CPython [aiohttp-v3.9.1.](https://docs.aiohttp.org/) client i.e. https://docs.aiohttp.org/en/stable/client_quickstart.html
This replaces #752 and #724 and requires:
> micropython/aiohttp: Add aiohttp package.

- micropython/bundles/bundle-networking/manifest.py
- micropython/umqtt.simple/manifest.py
- micropython/umqtt.simple/umqtt/simple.py
- micropython/urllib.urequest/manifest.py
- micropython/urllib.urequest/urllib/urequest.py
- python-ecosys/requests/manifest.py
- python-ecosys/requests/requests/__init__.py
- python-stdlib/ssl/manifest.py
- python-stdlib/ssl/ssl.py
This changes correspond to [micropython/12259](https://github.com/micropython/micropython/pull/12259).
> ssl: restructure micropython interface in a tls module

- python-stdlib/hmac/hmac.py
- python-stdlib/hmac/manifest.py
- python-stdlib/hmac/test_hmac.py
> python-stdlib/hmac/hmac: Fix for hashlib.

- python-ecosys/aiohttp/aiohttp/__init__.py
- python-ecosys/aiohttp/manifest.py
> python-ecosys/aiohttp: Fix binary data treatment.

- python-stdlib/tarfile-write/manifest.py
- python-stdlib/tarfile-write/tarfile/write.py
This change fixes issue https://github.com/micropython/micropython-lib/issues/797 which I opened a couple of days ago.
More context to be found there.
This is my first PR in which I tried to be neater, hope it'll get reviewed by someone :)
thanks
ubi
> python-stdlib/tarfile: Fixed permissions when adding to archive.

- tools/ci.sh
Attempt to un-break the manifest build. Depends on https://github.com/micropython/micropython/pull/13655
> ci: Add unix-ffi library when building unix-ffi subdirectory.

- micropython/lora/lora-sx126x/lora/sx126x.py
- micropython/lora/lora-sx126x/manifest.py
- micropython/lora/lora-sx127x/lora/sx127x.py
- micropython/lora/lora-sx127x/manifest.py
- micropython/lora/lora-sync/lora/sync_modem.py
- micropython/lora/lora-sync/manifest.py
- micropython/lora/lora/lora/modem.py
Collection of small LoRa fixes in individual commits. See commit messages for more details.
* SX126x: Fix invalid configuration after reset. Configuring with the documented minimal `lora_cfg` didn't produce the documented results, some configuration keys always needed to be set.
* SX126x: Fix syncword setting. Closes #796.
* SX127x: Fix syncword setting. Implementation was simply missing. :facepalm: 
* lora-sync: Fix a possible race where a send which failed immediately (or completed very quickly) would not return immediately.
* SX126x: Cosmetic clean up of some struct formatting.
Test on SX1276, SX1262, STM32WL55.
> lora: Multiple small fixes (including syncword, sx126x minimum config)

- python-stdlib/gzip/gzip.py
- python-stdlib/gzip/manifest.py
And give the `mode` parameter a default, matching CPython.
> gzip: Fix recursion error in open() function.

- unix-ffi/README.md
- unix-ffi/_markupbase/manifest.py
- unix-ffi/email.charset/manifest.py
- unix-ffi/email.encoders/manifest.py
- unix-ffi/email.feedparser/manifest.py
- unix-ffi/email.header/manifest.py
- unix-ffi/email.internal/manifest.py
- unix-ffi/email.message/manifest.py
- unix-ffi/email.parser/manifest.py
- unix-ffi/email.utils/manifest.py
- unix-ffi/fcntl/manifest.py
- unix-ffi/getopt/manifest.py
- unix-ffi/gettext/manifest.py
- unix-ffi/glob/manifest.py
- unix-ffi/html.parser/manifest.py
- unix-ffi/http.client/manifest.py
- unix-ffi/machine/manifest.py
- unix-ffi/multiprocessing/manifest.py
- unix-ffi/os/manifest.py
- unix-ffi/pwd/manifest.py
- unix-ffi/re/manifest.py
- unix-ffi/select/manifest.py
- unix-ffi/signal/manifest.py
- unix-ffi/sqlite3/manifest.py
- unix-ffi/time/manifest.py
- unix-ffi/timeit/manifest.py
- unix-ffi/ucurses/manifest.py
- unix-ffi/urllib.parse/manifest.py
And describe how to use `add_library()` instead.
> unix-ffi: Remove "unix_ffi" argument from require().

- python-stdlib/ssl/manifest.py
- python-stdlib/ssl/ssl.py
axtls doesn't define all the CERT_xxx constants, nor the MBEDTLS_VERSION constant.
This change means that `tls.SSLContext` is imported into the module, but that's subsequently overridden by the class definition in this module.
> ssl: Use "from tls import *" to be compatible with axtls.

- micropython/usb/README.md
- micropython/usb/examples/device/cdc_repl_example.py
- micropython/usb/examples/device/hid_custom_keypad_example.py
- micropython/usb/examples/device/keyboard_example.py
- micropython/usb/examples/device/midi_example.py
- micropython/usb/examples/device/mouse_example.py
- micropython/usb/usb-device-cdc/manifest.py
- micropython/usb/usb-device-cdc/usb/device/cdc.py
- micropython/usb/usb-device-hid/manifest.py
- micropython/usb/usb-device-hid/usb/device/hid.py
- micropython/usb/usb-device-keyboard/manifest.py
- micropython/usb/usb-device-keyboard/usb/device/keyboard.py
- micropython/usb/usb-device-midi/manifest.py
- micropython/usb/usb-device-midi/usb/device/midi.py
- micropython/usb/usb-device-mouse/manifest.py
- micropython/usb/usb-device-mouse/usb/device/mouse.py
- micropython/usb/usb-device/manifest.py
- micropython/usb/usb-device/tests/test_core_buffer.py
- micropython/usb/usb-device/usb/device/__init__.py
- micropython/usb/usb-device/usb/device/core.py
High-level support packages for creating USB device functionality in Python code.
These modules rely on the machine.USBDevice() object newly merged for MicroPython 1.23 (https://github.com/micropython/micropython/pull/9497).
**IMPORTANT**: The latest version of this PR requires a low-level change in MicroPython's USBDevice that was merged in https://github.com/micropython/micropython/pull/14253 - nightly builds from before 18 April 2024 do not have this change, and will fail in unexpected ways!!
This PR requires a nightly build of Micropython 1.23-preview or later, on a port with machine.USBDevice support (currently samd or rp2).
Can either edit manifest.py to freeze usb-device packages into the firmware, or use the following command to install packages directly from this PR:
```
$ …
```
> usb: Add high-level USB device support packages

- micropython/net/ntptime/manifest.py
- micropython/net/ntptime/ntptime.py
Fix a bug in the NTP client, where it would report the wrong time after 7 Feb 2036.
The NTP timestamp has a 32-bit count of seconds, which will wrap back to zero on 7 Feb 2036 at 06:28:16.
It's now March 2024. So we know that timestamps less than 1st Jan 2024 are impossible. So if the timestamp appears to be earlier than 1st Jan 2024, that probably means that the NTP time wrapped at 2^32 seconds. (Or someone set the wrong time on their NTP server, but we can't really do anything about that). So in that case, we need to add in those extra 2^32 seconds, to get the correct timestamp.
This means that this code will work until the year 2160.
(More precisely, this code will not work after 7th Feb 2160 at 06:28:15. Fixing that is someone else's problem, some time in the far future, by adjusting …
> ntptime: Year 2036 fix.

- micropython/espflash/espflash.py
- micropython/lora/lora-async/lora/async_modem.py
- pyproject.toml
This is a pretty straightforward lint and fix, should save a small amount of bytecode.
> all: Enable Ruff lint F541 'f-string without any placeholders'.

- micropython/bluetooth/aioble/examples/l2cap_file_client.py
- micropython/bluetooth/aioble/examples/l2cap_file_server.py
- micropython/bluetooth/aioble/examples/temp_client.py
- micropython/bluetooth/aioble/examples/temp_sensor.py
- micropython/bluetooth/aioble/multitests/ble_buffered_characteristic.py
- micropython/bluetooth/aioble/multitests/ble_characteristic.py
- micropython/bluetooth/aioble/multitests/ble_descriptor.py
- micropython/bluetooth/aioble/multitests/ble_notify.py
- micropython/bluetooth/aioble/multitests/ble_shutdown.py
- micropython/bluetooth/aioble/multitests/ble_write_capture.py
- micropython/bluetooth/aioble/multitests/ble_write_order.py
- micropython/bluetooth/aioble/multitests/perf_gatt_notify.py
- micropython/bluetooth/aioble/multitests/perf_l2cap.py
- micropython/drivers/display/lcd160cr/lcd160cr.py
- micropython/drivers/display/lcd160cr/lcd160cr_test.py
- micropython/drivers/storage/sdcard/sdtest.py
- pyproject.toml
- python-ecosys/aiohttp/aiohttp/__init__.py
- python-ecosys/aiohttp/examples/client.py
- python-ecosys/aiohttp/examples/compression.py
- python-ecosys/aiohttp/examples/get.py
- python-ecosys/aiohttp/examples/headers.py
- python-ecosys/aiohttp/examples/methods.py
- python-ecosys/aiohttp/examples/params.py
- python-ecosys/aiohttp/examples/ws.py
- python-ecosys/aiohttp/examples/ws_repl_echo.py
- python-ecosys/iperf3/iperf3.py
Mostly small cleanups, and explicit disable for examples/tests which insert the current directory into the path before importing.
> all: Enable ruff E401,E402 import lints.

- python-ecosys/aiohttp/aiohttp/aiohttp_ws.py
- python-ecosys/aiohttp/manifest.py
The function `binascii.b2a_base64()` returns a `bytes`.
Here needs a `string`
Otherwise, the value of `Sec-WebSocket-Key` in the headers will be `b'<BASE64-ENCODED_RANDOM_VALUE>'`.
It means there will be `b'` at the beginning and `'` at the end.
> aiohttp: Fix type of `Sec-WebSocket-Key` in `aiohttp_ws.py`

- python-stdlib/pathlib/pathlib.py
- python-stdlib/pathlib/tests/test_pathlib.py
Now works due to https://github.com/micropython/micropython/pull/10844#issuecomment-1554135154.
Code is still valid with older versions of micropython, just the actual rtruediv operations won't work (they previously still didn't work, so no change in functionality).
> python-stdlib/pathlib: Add __rtruediv__ magic method to pathlib.Path

- micropython/bluetooth/aioble/examples/temp_client.py
Only read from the temp characteristic if the connection is still
active. Improves the example by avoiding a TypeError exception when the
sensor disconnects.
> aioble/examples/temp_client.py: check connection before reading temp

- micropython/bluetooth/aioble/aioble/device.py
If the client disconnects immediately after connection, the irq can be run before the initial connect handler has finished.
> aioble/peripheral: Handle immediate disconnect.

- micropython/bluetooth/aioble-core/manifest.py
- micropython/bluetooth/aioble/aioble/device.py
- micropython/bluetooth/aioble/manifest.py
The value for the `timeout_ms` optional argument to `DeviceConnection.disconnected()` async method is changed from 60000 to None. This way users awaiting a device disconnection using `await connection.disconnected()` won't be surprised by a 1 minute timeout. For instance, in the `temp_sensor.py` usage example I think it's reasonable to expect the connection to the client to stay open indefinitely.
> aioble/device.py: No default timeout for async disconnected() method.

- micropython/bluetooth/aioble-peripheral/manifest.py
- micropython/bluetooth/aioble/aioble/peripheral.py
- micropython/bluetooth/aioble/manifest.py
When multiple UUIDs of the same size are advertised, they should all be listed in a single LTV.  Supplement to the Bluetooth Core Specification, Part A, §1.1.1:  "A packet or data block shall not contain more than one instance for each Service UUID data size."
When aioble construct the advertisement data, it is creating a new data block for each UUID that contains only that single UUID.  Rather than, e.g., a single 16-bit UUID block with a list of multiple UUIDs.
Not only is this against the specification, it wastes two bytes of limited advertisement space per UUID beyond the first for the repeated data block length and type fields.
Fix this by grouping each UUID size together.
> micropython/aioble: Place multiple UUIDs in single advertisement LTV.

- micropython/bluetooth/aioble-central/manifest.py
- micropython/bluetooth/aioble/aioble/central.py
- micropython/bluetooth/aioble/manifest.py
- micropython/bluetooth/aioble/multitests/ble_advertise_services.py
- micropython/bluetooth/aioble/multitests/ble_advertise_services.py.exp
- micropython/bluetooth/aioble/multitests/ble_write_capture.py.exp
- micropython/bluetooth/aioble/multitests/perf_gatt_notify.py
- micropython/bluetooth/aioble/multitests/perf_gatt_notify.py.exp
- micropython/bluetooth/aioble/multitests/perf_l2cap.py
- micropython/bluetooth/aioble/multitests/perf_l2cap.py.exp
Following on from #787 , this makes a similar fix on the central side:
- There may be more than one UUID per advertising field.
- The UUID advertising field may be empty (no UUIDs).
- Constructing 32-bit `bluetooth.UUID()` entities, which must be done by passing in a 4-byte bytes object, not an integer.
A multitest is added for these cases.
Also, other minor fixups for the multitests.
> aioble: fix `ScanResult.services` decoding of UUIDs, and add/improve multitests

- unix-ffi/pyusb/examples/lsusb.py
- unix-ffi/pyusb/manifest.py
- unix-ffi/pyusb/usb/__init__.py
- unix-ffi/pyusb/usb/control.py
- unix-ffi/pyusb/usb/core.py
- unix-ffi/pyusb/usb/util.py
This implements a compatible subset of the PyUSB library, for MicroPython unix (using ffi and `libusb-1.0.so`).
> pyusb: Add MicroPython implementation of PyUSB library.

- python-ecosys/requests/manifest.py
- python-ecosys/requests/requests/__init__.py
- python-ecosys/requests/test_requests.py
This removes all the hard-coded request headers from the requests module so they can be overridden by user provided headers dict.
Furthermore allow streaming request data without chunk encoding in those cases where content length is known but it's not desirable to load the whole content into memory. Also some servers (e.g. nginx) reject HTTP/1.0 requests with the Transfer-Encoding header set.
The change should be backwards compatible as long as the user hasn't provided any of the previously hard-coded headers.
> requests: Make possible to override headers and allow raw data upload.

- .github/workflows/package_tests.yml
- python-stdlib/contextlib/contextlib.py
- python-stdlib/contextlib/manifest.py
- python-stdlib/contextlib/tests.py
- python-stdlib/datetime/test_datetime.py
- python-stdlib/fnmatch/test_fnmatch.py
- python-stdlib/hashlib/tests/test_sha256.py
- python-stdlib/quopri/test_quopri.py
- tools/ci.sh
All of the runable package tests are run together in the new `ci.sh` function.  This is added to a new GitHub workflow to test the packages as part of CI.
Eventually it would be good to unify all the package tests to use `unittest`.
> github/workflows: Add workflow to run package tests.

- python-stdlib/unittest-discover/manifest.py
- python-stdlib/unittest-discover/tests/sub/sub.py
- python-stdlib/unittest-discover/tests/sub/test_module_import.py
- python-stdlib/unittest-discover/unittest/__main__.py
When running tests from subfolders, import by "full dotted path" rather than just module name, removing the need to add the test parent folder to sys.path.
---
I found a problem with unittest-discover in a project which uses microdot. A recent update in microdot includes a `test_client.py` in the src folder, which caused it to be pulled in when freezing the module via manifest, and this test file was also then run with `unittest discover`.
The issue is related to import path ordering. [The unit test in question](https://github.com/miguelgrinberg/microdot/blob/main/src/microdot/test_client.py) starts with `from microdot.microdot import Request, Response, AsyncBytesIO` which seems reasonable. The microdot package has this `microdot/microdot.py` file and that import line works fine normally. …
> unittest/discover: Reverse order of parent/top in sys.path.

- python-stdlib/logging/logging.py
- python-stdlib/logging/manifest.py
Otherwise there's a crash on line 70 where `level` is not a property of the class unless explicitly set with ::setLevel
> StreamHandler should call parent constructor

- micropython/usb/usb-device-cdc/manifest.py
- micropython/usb/usb-device-cdc/usb/device/cdc.py
If the CDC receive buffer was full and some code read less than 64 bytes (wMaxTransferSize), the CDC code would submit an OUT transfer with N<64 bytes length to fill the buffer back up.
However if the host had more than N bytes to send then it would still send the full 64 bytes (correctly) in the transfer. The remaining (64-N) bytes would be lost.
Fix is to not send a new transfer until 64 bytes is free. Adds the restriction that CDCInterface rxbuf has to be at least 64 bytes.
Closes #885.
*This work was funded through GitHub Sponsors.*
> usb-device-cdc: Fix lost data in read() path if short reads happened.

- tools/build.py
This points to the package's base directory of the within the micropython-lib directory structure.
> tools/build.py: Add "path" entry to index.json.

- tools/ci.sh
- unix-ffi/sqlite3/manifest.py
- unix-ffi/sqlite3/sqlite3.py
- unix-ffi/sqlite3/test_sqlite3.py
- unix-ffi/sqlite3/test_sqlite3_2.py
- unix-ffi/sqlite3/test_sqlite3_3.py
The current `sqlite.py` file only takes 4 bytes for pointers, disallowing 64 bit platforms, and also doesn't finalize statements except in the `Cursor.close()`, causing leaks and issues with `Connections.close()`. This PR fixes these issues by determining the pointer size dynamically for the platform, and finalizes the previous statements when a new one is made in `execute()`.
Along with these fixes, this PR also adds the ability to use `URI`, and `commit` & `rollback` functionality to increase similarity with the CPython sqlite3 module. The addition of `commit` & `rollback` includes the addition of the autocommit and transaction posibilities as with the CPython sqlite3 module, with the same default mode enabled here.
> unix-ffi/sqlite3: Fix 64 bit support, statement finalization, and add `UFI`, `commit`, and `rollback` support.

- CONTRIBUTING.md
I hadn't used this feature for a while, and realised there's one confusing element of it not previously mentioned in the docs.
> docs: Add some extra explanation of "Publish packages for branch"

- micropython/umqtt.robust/example_sub_robust.py
> umqtt.robust: Remove reference to missing example.

- micropython/usb/README.md
- micropython/usb/usb-device/manifest.py
- micropython/usb/usb-device/usb/device/core.py
The USB pending transfer flag was cleared before calling the completion callback, to allow the callback code to call submit_xfer() again.
Unfortunately this isn't safe in a multi-threaded environment, as another thread may see the endpoint is available before the callback is done executing and submit a new transfer.
Rather than adding extra locking, specifically treat the transfer as still pending if checked from another thread while the callback is executing.
Together with https://github.com/micropython/micropython/pull/15264 this closes #874.
Tested using the sample code from the linked issue.
*This work was funded through GitHub Sponsors.*
> usb: Fix USB device library transfer thread safety

- python-stdlib/base64/manifest.py
This base64 library only uses `struct.unpack` which is available in the built-in `struct` module, so no need for the micropython-lib extras.
> base64: Remove struct dependency from manifest.

- micropython/lora/lora-sx127x/lora/sx127x.py
- micropython/lora/lora-sx127x/manifest.py
The `_reg_update` method must be called after updating the implicit header option's bit.
> micropython/lora: Update the implicit header option in the _SX127x.

- micropython/usb/usb-device/manifest.py
- micropython/usb/usb-device/usb/device/core.py
To use this feature you need to create a usb device signaling remote wakeup and then enable remote wakeup on the host (on linux write `enabled` to `/sys/bus/usb/devices/<device>/power/wakeup`, or let `udev` do that). Then you can wake up the host when it is on standby using USBDevice.remote_wakeup.
See also [micropython#15262](https://github.com/micropython/micropython/pull/15262).
> usb-device: Allow signaling capability of remote_wakeup.

- micropython/bluetooth/aioble-central/manifest.py
- micropython/bluetooth/aioble-core/manifest.py
- micropython/bluetooth/aioble/aioble/central.py
- micropython/bluetooth/aioble/aioble/device.py
- micropython/bluetooth/aioble/manifest.py
In my project I am connecting using aioble to a human input device. There is noticeable input lag. Turns out the RTT latency is a little over 200ms (I test this by timing `await char.write(b'foo', response=1)`). I suspect this is because the BLE connection interval is being set to 100ms. The [gap_connect](https://docs.micropython.org/en/latest/library/bluetooth.html#bluetooth.BLE.gap_connect) function allows setting `min_conn_interval_us` and `max_conn_interval_us`, however there is no way to do so using aioble.
This PR allows the following additional arguments to be passed to `device.connect()`:
* scan_duration_ms
* min_conn_interval_us
* max_conn_interval_us
These are passed as-is to `gap_connect()`. The default value for all of these is `None`, which causes gap_connect to use its own …
> aioble: Pass additional connection arguments to gap_connect.

- micropython/umqtt.simple/manifest.py
- micropython/umqtt.simple/umqtt/simple.py
Problem statement:
If there are any network issues, mqtt will block on socket non-deterministically.
In such cases, only way to come out of the blocking is to reboot using watch dog timers.
This is costly solution.
Solution:
Alternatively, developer can set the max timeout for the socket.
Upon any issue, mqtt lib will throw exception. Developer can catch it, take
right actions like, restarting the task without rebooting the whole device.
This brings determinism and gives the control to developer to choose right time for her/his use case. This fix works for async applications too.
(I plan to make whole umqtt async compatible.)
> settimeout for mqtt socket

- micropython/aioespnow/README.md
- micropython/net/webrepl/webrepl.py
Sibling PR of https://github.com/micropython/micropython/pull/16155. Removes the deprecated network.[AP|STA]_IF form.
This work was funded through GitHub Sponsors.
> aioespnow, webrepl: Use recommended network.WLAN.IF_[AP|STA] constants.

- python-stdlib/unittest/tests/exception.py
- python-stdlib/unittest/tests/test_subtest.py
- python-stdlib/unittest/unittest/__init__.py
- tools/ci.sh
This refactors things slightly so that `SkipTest` exceptions are handled correctly within a sub-test context manager.
Also enabled `unittest` tests on CI.
> unittest: Allow SkipTest to work within a subTest.

- python-stdlib/unittest/manifest.py
- python-stdlib/unittest/unittest/__init__.py
So this code can be compiled with the MicroPython native emitter, which does not support "raise" without any arguments.
> unittest: Always use "raise" with an argument.

- python-ecosys/requests/requests/__init__.py
- python-ecosys/requests/test_requests.py
The requests() function takes a headers dict argument (call-by-reference). This object is then modified in the function. For instance the host is added and authentication information. Such behavior is not expected. It is also problematic:
- Modifications of the header dictionary will be visible on the caller site.
- When reusing the same (supposedly read-only) headers object for differenct calls, the second call will apparently re-use wrong headers from the previous call and may fail.
This patch should also fix #839. Unfortunately the copy operation does not preserve the key order and we have to touch the existing test cases.
> requests: Do not leak header modifications when calling request.

- micropython/mip/manifest.py
- micropython/mip/mip/__init__.py
This PR allows URLs in package.json files to be specified relative to the directory containing the `package.json` file. This mirrors the functionality added to mpremote in [micropython:#12477](https://github.com/micropython/micropython/pull/12477).
This simplifies use of mip packages from forked or copied repos.
Example package.json:
```
{
"urls": [
["ota/rollback.py", "rollback.py"],
["ota/status.py", "status.py"],
["ota/update.py", "update.py"],
["ota/blockdev_writer.py", "blockdev_writer.py"]
],
"deps": [
],
"version": "0.2"
}
```
> micropython/mip: Allow relative URLs in package.json files.

- .github/workflows/build_packages.yml
> github/workflows: Update actions/upload-artifact to v4.

- micropython/mip/manifest.py
- micropython/mip/mip/__init__.py
If a ROMFS is mounted then "/rom/lib" is usually in `sys.path` before the writable filesystem's "lib" entry.  The ROMFS directory cannot be installed to, so skip it if found.
Tested on PYBD_SF2.
Prior to this PR:
```
>>> import mip
>>> mip.install('unittest')
Installing unittest (latest) from https://micropython.org/pi/v2 to /rom/lib
Copying: /rom/lib/unittest/__init__.mpy
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "mip/__init__.py", line 1, in install
File "mip/__init__.py", line 1, in _install_package
File "mip/__init__.py", line 1, in _install_json
File "mip/__init__.py", line 1, in _download_file
File "mip/__init__.py", line 1, in _ensure_path_exists
AttributeError: 'VfsRom' object has no attribute 'mkdir'
```
With this PR applied:
```
>>> import sys …
```
> mip: Make mip.install() skip /rom*/lib directories.

- micropython/umqtt.simple/manifest.py
- micropython/umqtt.simple/umqtt/simple.py
Commit 35d41dbb0e4acf1518f520220d405ebe2db257d6 changed the API for using SSL with umqtt, but only did a minor version increase.  This broke various uses of this library, eg
https://github.com/aws-samples/aws-iot-core-getting-started-micropython
Reinstate the original API for specifying an SSL connection.  This library now supports the following:
- default, ssl=None or ssl=False: no SSL
- ssl=True and optional ssl_params specified: use ssl.wrap_socket
- ssl=<SSLContext instance>: use provided SSL context to wrap socket
TODO
> umqtt.simple: Restore legacy ssl/ssl_params arguments.

- micropython/drivers/radio/nrf24l01/nrf24l01.py
According to the datasheet of the NRF240L1 chip, 150 μs startup time is only acceptable when the chip is clocked externally. Most modules use crystal, which require 1.5 ms to settle. I think it's okay to wait more in both cases, for a reliable startup.
---
ref: "6.1.7 Timing Information" in nRF24L01+ datasheet rev. 1.0
Without this patch I couldn't make my module to transmit reliably.
> drivers/radio/nrf24l01: Increase startup delay.

- micropython/drivers/radio/nrf24l01/nrf24l01.py
The timeout condition was not handled before. Upon timeout, this caused the chip to stay active until another send command changed it's state.
Sometimes when it was unable to transmit the data, it got stuck in the tx fifo causing it to fill up over time, which set the TX_FULL flag in the STATUS register.
Since there was no exceptions raised, the user code could not differentiate a successful send or a timeout condition.
----
Note: timeout condition almost always indicate HW failure or improper control of the chip.
> drivers/radio/nrf24l01: Properly handle timeout.

- micropython/drivers/radio/nrf24l01/manifest.py
- micropython/drivers/radio/nrf24l01/nrf24l01.py
The value of the STATUS register is always transmitted by the chip when reading any command. So a R_REGISTER command and the turnaround time can be spared by issuing a NOP command instead.
This implementation suggested by the datasheet.
This operation is compatible with both nRF24L01 and nRF24L01+.
----
In my testing, this reduced the STATUS read time from 41 μs to 27 μs. This allows for quicker polling, and thus more responsive operation. 
Old behavior:
New behavior:
> drivers/radio/nrf24l01: Optimized status reading.

- unix-ffi/machine/machine/timer.py
- unix-ffi/machine/manifest.py
Newer implementations of libc integrate the functions from librt, for example glibc since 2.17 and uClibc-ng. So if the librt.so cannot be loaded, it can be assumed that libc contains the expected functions.
> unix-ffi/machine/timer: Use libc if librt is not present

- python-ecosys/aiohttp/aiohttp/__init__.py
- python-ecosys/aiohttp/manifest.py
According to RFC (https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) header names are case-insensitive.
This PR makes sure that the module behaves consistently regardless of the casing of `Content-type` and `Content-Length` (other headers are not considered by the module)
Without this fix, the client seems to wait for the connection termination (~10 seconds) prior to returning any content if the casing of `Content-Length` is different.
> python-ecosys/aiohttp: fix header - case-insensitivity

- python-ecosys/aiohttp/aiohttp/__init__.py
- python-ecosys/aiohttp/aiohttp/aiohttp_ws.py
- python-ecosys/aiohttp/manifest.py
Latest version of aiohttp:
When making connection to a Websocket, the header argument is ignored.
The consequence is that you cannot make a connection to most online MQTT broker's over websocket
because they need the header entry: **"Sec-WebSocket-Protocol":"mqtt"** in the handshake of
the upgrade protocol.
See this small example code:
It connects to a MQTT broker and then sends the CONNECT mqtt packet.
Then it should get a reply of **opcode:2, data: b' \x02\x00\x00'** where 'data' is a CONNACK mqtt package
Because of the missing header entry **"Sec-WebSocket-Protocol":"mqtt"** most brokers will refuse the connection or
refuse to accept MQTT packets.
```python
import aiohttp
import asyncio
async def connect():
url = "ws://test.mosquitto.org:8080"
headers = …
```
> aiohttp: fix header problem

- micropython/usb/usb-device-cdc/manifest.py
- micropython/usb/usb-device-cdc/usb/device/cdc.py
Only allocate a memoryview when the (first) write was partial.
> usb/cdc: writing small blocks should not require allocation

- python-stdlib/inspect/inspect.py
- python-stdlib/inspect/manifest.py
- python-stdlib/inspect/test_inspect.py
- tools/ci.sh
Fix the `isgenerator()` logic.
Also optimise both `isgenerator()` and `isgeneratorfunction()` so they use the same lambda, and don't have to create it each time they are called.
And add some basic unit tests for this package.
Fixes issue #997.
> inspect: Fix isgenerator logic.

- micropython/utop/README.md
- micropython/utop/manifest.py
- micropython/utop/utop.py
Implements a new module, `utop`, as suggested in https://github.com/micropython/micropython/pull/12732#issuecomment-1790040708.
Currently only works on the `esp32` port, and requires https://github.com/micropython/micropython/pull/12732.
An animated GIF to demonstrate what the output looks like:
Opted to give it a generic name instead of ESP32-specific, as there was mention of other platforms also having options to retrieve runtime performance data, which might be nice to support at a later time.
Compared to the version posted in that `esp32` MR ([here](https://github.com/micropython/micropython/blob/e2316bd17741dd74e49faa1efdea89712695657b/docs/library/esp32.rst#functions)) this version is a few lines longer to make it a bit easier to read and expand later. For example it includes an …
> Implement the utop module

- tools/verifygitlog.py
This includes the following commits:
- Allow long co-author and sign-off names (https://github.com/micropython/micropython/pull/17302).
- Disallow a leading slash in commit subject line (https://github.com/micropython/micropython/pull/17294).
- Apply stricter rules on git subject line (https://github.com/micropython/micropython/pull/15823).
- Show invalid commit subjects in quotes (https://github.com/micropython/micropython/pull/16465).
> tools/verifygitlog.py: Sync with changes from the main repo.

- micropython/aiorepl/aiorepl.py
- micropython/aiorepl/manifest.py
raw repl mode is generally  used as a command channel where all stdio traffic is related directly to the raw commands and responses sent. 
For this to work in aiorepl we need to ensure background tasks don't sent/receive anything on stdio else the command channel will be corrupted.
The simplest way to achieve this is to make the raw commands blocking rather than asyncio, assuming the user wont leave the device in raw mode for too long at any one time.
> micropython/aiorepl: Use blocking reads for raw_repl.

- python-stdlib/logging/logging.py
- python-stdlib/logging/manifest.py
Although `Logger.exception` supports passing exception info with `exc_info`, when you use `logging.exception`, keyword arguments are not forwarded to the root logger, which makes passing `exc_info` raise TypeError.
> logging: Allow logging.exception helper to handle tracebacks.

- python-stdlib/abc/abc.py
- python-stdlib/abc/manifest.py
this trivial addition will allow less code differences between standard python classes and micropython code.
> abc: add ABC base class

- python-stdlib/inspect/inspect.py
- python-stdlib/inspect/manifest.py
- python-stdlib/inspect/test_inspect.py
This implements a very basic `inspect.signature()` function.
At the moment it returns only a simple `Signature` instance with a `parameters` attribute that holds an `OrderedDict` whose length matches the arity of the input function (the number of arguments it takes).
So, the following code works and is compatible with CPython:
```py
def f(a, b, *, c):
pass
print(len(inspect.signature(f).parameters))
```
That should print `3`.
I tested this on unix 64-bit, unix nanbox (32-bit), webassembly (32-bit) and a 32-bit bare-metal target.
-------
The main aim here is to support PyScript which is currently using a very unreliable hack to work out if a Python function takes arguments or not: https://github.com/pyscript/pyscript/blob/main/core/src/stdlib/pyscript/events.py#L96-L126
> inspect: Implement a very basic signature function.
